#!/bin/bash
export_ () { export $1="$2"; }

export_ \
    MONTY_CLONE \
    ${__BLESSED_ROOT__}/__build__/monty.git

export_ \
    MONTY_ACTIVATION_SCRIPT \
    ${MONTY_CLONE}/gitprompt.sh

${__BLESSED_DOT__} ${__BLESSED_CLIENT__}.$*
