src=https://github.com/magicmonty/bash-git-prompt
initial_commit=6f4c272200fb6f72a2f1442b2894c6d7cf8cc0a7
target_commit=148d502b666a0d62ecc83680817596b097a70f2a

dst=${MONTY_CLONE}

[ "$1" = "-f" ] && rm -rf ${MONTY_CLONE}
[ -d ${dst}   ] && echo "Already installed. Use '-f' to reinstall."
[ -d ${dst}   ] || {
    git clone ${src} ${dst} 
    pushd ${dst}
    git checkout ${target_commit}
    popd
}

